In [1]:
import numpy as np

### Q1.Create a 1D NumPy array with values from 10 to 50 (inclusive).

In [ ]:
#arr1d= np.array((10,50)) # [10,50] NOT CORRECT
arr1d= np.arange(10,51)
arr1d 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### 2. Create a 5x5 matrix of all zeros.

In [6]:
arr2d= np.zeros((5,5))
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 3. Create a 4x3 matrix filled with value 9.

In [7]:
arr2d= np.full((4,3), fill_value=9)
arr2d

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

### Generate 20 random integers between 100 and 500.

In [22]:
#arr1d= np.random.randint(100,500,(4,5))
arr1d= np.random.randint(100,500,20)
arr1d 

array([344, 499, 156, 470, 330, 226, 448, 338, 263, 230, 457, 318, 221,
       433, 334, 436, 479, 247, 207, 458], dtype=int32)

### Create an array of 100 evenly spaced numbers between 0 and 10.

In [79]:
arr1d = np.round(np.linspace(0,10,100),2)
arr1d

array([ 0.  ,  0.1 ,  0.2 ,  0.3 ,  0.4 ,  0.51,  0.61,  0.71,  0.81,
        0.91,  1.01,  1.11,  1.21,  1.31,  1.41,  1.52,  1.62,  1.72,
        1.82,  1.92,  2.02,  2.12,  2.22,  2.32,  2.42,  2.53,  2.63,
        2.73,  2.83,  2.93,  3.03,  3.13,  3.23,  3.33,  3.43,  3.54,
        3.64,  3.74,  3.84,  3.94,  4.04,  4.14,  4.24,  4.34,  4.44,
        4.55,  4.65,  4.75,  4.85,  4.95,  5.05,  5.15,  5.25,  5.35,
        5.45,  5.56,  5.66,  5.76,  5.86,  5.96,  6.06,  6.16,  6.26,
        6.36,  6.46,  6.57,  6.67,  6.77,  6.87,  6.97,  7.07,  7.17,
        7.27,  7.37,  7.47,  7.58,  7.68,  7.78,  7.88,  7.98,  8.08,
        8.18,  8.28,  8.38,  8.48,  8.59,  8.69,  8.79,  8.89,  8.99,
        9.09,  9.19,  9.29,  9.39,  9.49,  9.6 ,  9.7 ,  9.8 ,  9.9 ,
       10.  ])

### Create a 3×3 identity matrix.

In [28]:
arr2d= np.eye(3,3)
arr2d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create an array [1, 2, 3] but with dtype=float32.


In [34]:
arr1d= np.array([1,2,3],dtype=float)
arr1d

array([1., 2., 3.])

### Create a 2D array from the list [[1, 'a'], [2, 'b']]. What will be the dtype? Why?

In [37]:
l=[[1, 'a'], [2, 'b']]
#type(l) list
arr2d= np.reshape(l,(2,2))
arr2d

array([['1', 'a'],
       ['2', 'b']], dtype='<U21')

In [69]:
arr1d= np.array([[1, 'a'], [2, 'b']])
arr1d

array([['1', 'a'],
       ['2', 'b']], dtype='<U21')

### Create a 10×10 array of random numbers and find its shape.

In [81]:
arr2d=np.random.rand(10,10)
arr2d

array([[0.46267249, 0.44520611, 0.8483739 , 0.13991501, 0.93846656,
        0.75170266, 0.4013911 , 0.56950776, 0.39581475, 0.26225318],
       [0.03614023, 0.40629682, 0.93570783, 0.09975246, 0.17795792,
        0.25719754, 0.98977182, 0.57405922, 0.09537817, 0.75601153],
       [0.11860389, 0.21372097, 0.75938294, 0.90768149, 0.05666471,
        0.45404163, 0.01285325, 0.91533936, 0.17694729, 0.97499595],
       [0.01659831, 0.77152841, 0.08284773, 0.89694641, 0.5756873 ,
        0.59922893, 0.94183689, 0.98265146, 0.31235907, 0.01153198],
       [0.84787893, 0.2448346 , 0.21091277, 0.01235546, 0.81378675,
        0.70103288, 0.85554212, 0.44982411, 0.83880671, 0.7050129 ],
       [0.06966773, 0.5572511 , 0.76668678, 0.1910703 , 0.7813044 ,
        0.42775876, 0.74863425, 0.33389397, 0.83178974, 0.770151  ],
       [0.44737375, 0.52564126, 0.09909053, 0.18002463, 0.79857798,
        0.85389408, 0.8623305 , 0.42591159, 0.35378104, 0.94672811],
       [0.94127349, 0.7977383 , 0.4492190

### Create an array with 30 values using np.arange. Then reshape it into a 5×6 matrix.

In [68]:
arr1d= np.arange(30).reshape(5,6)
arr1d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
arr1d= np.arange(0,1,0.1)
arr1d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [72]:
arr1d= np.linspace(0,1,10)
arr1d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Given arr = np.arange(1, 11) Extract elements: [3, 4, 5, 6]

In [82]:
arr1d = np.arange(1,11)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.extract([3,4,5,6],arr1d)

array([1, 2, 3, 4])

### Reverse the array using slicing.

In [86]:
arr_rev= arr1d[::-1]
arr_rev

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Given a 5×5 matrix, extract the center 3×3 block.

In [87]:
arr2d= np.random.rand(5,5)
arr2d

array([[0.29860401, 0.44085076, 0.1883615 , 0.28604946, 0.99922822],
       [0.70374162, 0.76300096, 0.7419812 , 0.6825141 , 0.05980319],
       [0.41972796, 0.00490029, 0.52294725, 0.89982434, 0.82752429],
       [0.6253094 , 0.73113602, 0.68868963, 0.73626322, 0.57431111],
       [0.35956252, 0.2798404 , 0.8134675 , 0.89311281, 0.66726286]])

In [90]:
arr2d[1:4, 1:4]

array([[0.76300096, 0.7419812 , 0.6825141 ],
       [0.00490029, 0.52294725, 0.89982434],
       [0.73113602, 0.68868963, 0.73626322]])

### Extract every 3rd element from index 2 to 20.

In [101]:
arr1d= np.random.randint(10,60,30)
arr1d


array([18, 24, 46, 11, 51, 26, 18, 39, 23, 20, 12, 19, 52, 50, 13, 32, 49,
       57, 58, 54, 37, 46, 50, 19, 24, 35, 44, 26, 45, 22], dtype=int32)

In [102]:
arr1d[2:21:3]

array([46, 26, 23, 19, 13, 57, 37], dtype=int32)

### From a 4×4 matrix, extract the diagonal using slicing (no loops).

In [109]:
arr2d=np.array([[10,20,30],
 [40,50,60],
 [70,80,90]])
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [114]:
arr2d[0:, 1:2]

array([[20],
       [50],
       [80]])

### Explain if this returns a view or copy:
b = a[1:4]  => it will create a view

### Extract all rows except the first and last.

In [125]:
x = np.arange(10)
y = x[3:7]
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
y[0] = 548
y

array([548,   4,   5,   6])

In [128]:
x

array([  0,   1,   2, 548,   4,   5,   6,   7,   8,   9])

In [129]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
b=a[:, 1:3]
b

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [131]:
b[0,0]=999
a

array([[  0, 999,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])